apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: tekton-node
  name: tekton-node-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-node
  template:
    metadata:
      labels:
        app: tekton-node
    spec:
      containers:
        - image: quay.io/openshift-pipeline/tekton-node/tekton-node-dep:latest
          imagePullPolicy: Always
          name: tekton-node
          ports:
            - containerPort: 9000
              protocol: TCP
