apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-dep-node
  name: pipeline-dep-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-dep-node
  template:
    metadata:
      labels:
        app: pipeline-dep-node
    spec:
      containers:
        - image: quay.io/openshift-pipeline/dep-node:latest
          imagePullPolicy: Always
          name: pipeline-dep-node
          ports:
            - containerPort: 9000
              protocol: TCP
