apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipeline-dep-node
  name: pipeline-dep-node
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: pipeline-dep-node
